use notify_debouncer_full::new_debouncer;
use cssparser::serialize_identifier;
use std::time::{Duration, Instant};
use std::io::{BufWriter, Write};
use std::collections::HashSet;
use once_cell::sync::lazy;
use std::fs::{self, File};
use seahash::SeaHasher;
use rayon::prelude::*;
use std::hash::Hasher;
use colored::Colorize;
use std::sync::Mutex;
use std::path::Path;
use sysinfo::System;
use memmap2::Mmap;
use regex::Regex;
